DAT(ILLEGAL_CHAR, "Illegal character")
DAT(READTABLE_CORRUPT, "Readtable is corrupt")
DAT(UNEXPECTED_RPAREN, "Unexpected right parenthesis")
DAT(UNEXPECTED_EOF, "Unexpected end of file")
DAT(INVALID_TMACRO, "Unsupported macro character")
DAT(INVALID_DOTTED_PAIR, "Invalid dotted pair notation")
DAT(STRING_TOO_LONG, "String too long")
DAT(CONSTITUENT_TOO_LONG, "Identifier too long")
DAT(BAD_FUNCTION, "Bad Function")
DAT(TOO_FEW_ARGS, "Too few arguments")
DAT(TOO_MANY_ARGS, "Too many arguments")
DAT(BAD_ARG_TYPE, "Bad argument type")
DAT(UNBOUND_FUNCTION, "Unbound function")
DAT(UNBOUND_VARIABLE, "Unbound variable")
DAT(DIVIDE_BY_ZERO, "Divide by zero")
DAT(OUT_OF_MEMORY, "Out of memory")
DAT(UNKNOWN_NODE_TYPE, "Unknown node type")
DAT(MATH_ERROR, "Math Error")
DAT(UNKNOWN_BLOCK_NAME, "Unknown Block Name in return")
DAT(UNKNOWN_ERROR, "Unknown Error")
DAT(EOF_IN_CONSOLE, "End of File in console")
DAT(FATAL_ERROR, "Fatal Error")
DAT(FILE_NOT_FOUND, "File not found")
DAT(STACK_OVERFLOW, "Stack Overflow")
DAT(ILLEGAL_NT_MACRO, "Illegal character following non-terminating macro")
DAT(INDEX_OUT_OF_BOUNDS, "Index on array or vector out of bounds")
DAT(DOTTED_PAIR, "Invalid dotted pair notation")
DAT(REDEF_CONSTANT, "Redefinition of constant not allowed")
DAT(REDEF_FORM, "Redefinition of special form not allowed")
DAT(INVALID_SYMBOL, "Invalid Symbol")
DAT(INVALID_PACKAGE_NAME, "Invalid Package Name")
DAT(NOT_A_FUNCTION, "Not a function")
DAT(STACK_CORRUPT, "Stack corrupt")
DAT(ARG_SHOULD_BE_GREATER_THAN_ZERO, "Argument should be greater than zero")
DAT(VECTOR_NOT_POINT, "A point should be a vector of three numbers")
DAT(INVALID_GRAPHIC_PRIMITIVE, "Graphic primitive must be composed of at least one point")
DAT(DOMAIN_ERROR, "Argument not in valid range")
DAT(INVALID_STREAM, "Stream is invalid")
DAT(BAD_KEYWORD, "Invalid keyword in function")
DAT(OBJECT_NOT_IN_ENV, "Object not in environment")
DAT(NO_COMPLEX_IN_LINK, "Cannot use an agent in creating a link")
DAT(NOT_SERIAL_AGENT, "Must be a serial agent")
DAT(NO_IK_AVAIL, "No inverse kinematics routine available")
DAT(IKLIB_NOT_VALID, "Inverse kinematics library not valid")
DAT(UNCAUGHT_EXCEPTION, "Exception not caught")

DAT(NUM_ERRMSGS, "System Error: Unknown error number")
